name: absensi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.3.4
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.10
  http: ^1.2.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  file_picker: ^8.1.7
  excel: ^4.0.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  lottie: ^3.3.0
  flutter_animate: ^4.5.2
  table_calendar: ^3.1.3
  location: ^7.0.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  qr_flutter: ^4.1.0
  barcode_scan2: any
  change_app_package_name: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/sports_event.png
    - assets/festival.png
    - assets/debate_event.png
    - assets/ppdb.png
    - assets/kartini.png
    - assets/LogoNoBg.png
    - assets/lottie/rocket.json
    - assets/lottie/education1.json
    - assets/lottie/education2.json
    - assets/lottie/education3.json
